name = "berlin2026"
version = "0.1.0"
defaultTargets = ["bobkonf", "leaning-in"]

[[require]]
name = "verso-slides"
git = "git@github.com:leanprover/verso-slides.git"
rev = "julias-berlin-2026-branch"

[[lean_lib]]
name = "Bobkonf"

[[lean_lib]]
name = "LeaningIn"

[[lean_exe]]
name = "bobkonf"
root = "Bobkonf"

[[lean_exe]]
name = "leaning-in"
root = "LeaningIn"
